services:
  db:
    image: postgres:16-alpine
    container_name: category_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: category_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
    container_name: category_api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/category_db
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  pgdata:
